commonfields:
  id: b88bbaf6-9bb5-4670-80f5-6d74911fc55c
  version: -1
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
dockerimage: demisto/python3:3.10.13.75921
enabled: true
engineinfo: {}
mainengineinfo: {}
name: FinalAutomation
pswd: ""
runas: DBotWeakRole
runonce: false
script: ""
scripttarget: 0
subtype: python3
tags: []
type: python
